version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  lint-fe:
    executor:
      name: node/default
      tag: "20.19.0"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run lint
          name: Lint JS code
  build-tauri:
    docker:
      - image: cimg/rust:1.74.1-node
    steps:
      - checkout
      - node/install:
          node-version: "20.19.0"
      - node/install-packages:
          pkg-manager: npm
      - run: sudo apt-get update -y
      - run: sudo apt-get install libglib2.0-dev
      - run: sudo apt-get install libgtk-3-dev
      - run: sudo apt-get install libsoup2.4-dev
      - run: sudo apt-get install libjavascriptcoregtk-4.0-dev
      - run: sudo apt-get install webkit2gtk-4.0-dev
      - run: sudo apt-get install libappindicator3-1
      - run: npm run tauri:build
workflows:
  build-all:
    jobs:
      - lint-fe
      - build-tauri
